model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: '{epoch:03d}'
  dirpath: 'data/models/${exp_name}'
  auto_insert_metric_name: false
  monitor: 'val/fixed_gaussian'
  mode: 'min'
  save_top_k: 10
  save_last: True